spring:
  application:
    name: dayonetest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/score
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
